version: '3.5'

networks:
  spark-net:
    name: my-spark-net
    driver: bridge

services:
  apache-spark:
    container_name: 'jupyter_lab_spark'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./.home:/home

#End-Of-Scripts
