version: '3.5'

networks:
  spark-net:
    name: my-spark-net
    driver: bridge

volumes:
  vol-sparkuser:

services:
  jupyterlab:
    container_name: 'jupyter_lab_spark'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - vol-sparkuser:/home
      - ./.notebooks:/opt/spark/notebooks

#End-Of-Scripts
